name: Standalone CLI
on: [push, pull_request]
jobs:
   machineStandalone:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: docker://docker.io/fluidattacks/skims:latest
           name: skimsStandalone
           with:
             args: skims scan ./pipeline-config.yml

         - name: Upload file
           uses: actions/checkout@v4
           if: always()
           with:
               name: fluid-attack-report
               path: ./fluid-attack-report.csv

